import java.util.Scanner;

public class LoginSystem {
    public static void main(String[] args) {
        String Correctusername = "user001";
        String CorrectPassword = "password";

        
        Scanner scanner = new Scanner(system.in);

        System.out.print(s:"Enter your username: ");
        String inputUsername = scanner.nextLine();

        System.out.print(s:"Enter your password: ")
        String inputPassword = scanner.nextLine();

        if (inputUsername.equals(Correctusername) && inputPassword.equals(CorrectPassword)) {
            System.out.println(x:"Login successful");
        } else {
            System.out.println(x:"Invalid username or password.");
        }
        user001
        scanner.close();
        }
    }
