import java.util.*;
public class DEMO7{
    public static void main(String[] args){
    string name;
    int age;
    long phno;
    Scanner sc = new scanner(System.in);
 
    
    System.out.println(x:"Enter the name");
    name = sc.nextline();
    System.out.println(x:"Enter the age");
    age = sc.nextInt();
    System.out.println(x:"Enter the phno");
    phno = sc.nextLong();
    System.out.println("Hello "+name+" ur age is"+age+" ur phno number is "+phno);
    }
}