import java.util.*;
class DEMO8{
    public static void main(String[] args){
        Scanner sc = new Scanner(System.in);
        string loginid;
        string pwd;
        string reply;
        do{
            System.out.println("Welcome to Malla Reddy University");
            System.out.println("Have you visited our site earlier");
            reply = sc.nextInt();
            if(reply == "no"){
                System.out.println(X:"Login Here");
                System.out.println(X:"Enter ur id and pwd");
                loginid = sc.nextLine();
                pwd = sc.nextLine();
            } else {
                System.out.println(X:"You are our valued customer");
            }
            
            } while (loginid.equals(anObject:"vasu")&& pwd.equals(anObject:"vasu"));

        }
    }
}  